name: CI (feature)

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      NEXT_TELEMETRY_DISABLED: '1'
      DATABASE_URL: 'file:./test.db'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npm run prisma:generate
        env:
          DATABASE_URL: 'file:./test.db'

      - name: Prepare test database (Prisma db push)
        run: npx prisma db push
        env:
          DATABASE_URL: 'file:./test.db'

      - name: Build
        run: npm run build

      - name: Test (Vitest with coverage)
        shell: bash
        run: |
          set -o pipefail
          npm run test:ci | tee vitest-output.txt
        env:
          DATABASE_URL: 'file:./test.db'

      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage/lcov-report/**
            coverage/lcov.info
          if-no-files-found: warn
          retention-days: 7

      - name: Upload vitest logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vitest-logs
          path: vitest-output.txt
          if-no-files-found: warn
          retention-days: 7

      - name: Job summary
        if: always()
        shell: bash
        run: |
          {
            echo "## CI results (feature)";
            echo "";
            echo "- Branch: ${{ github.ref_name }}";
            echo "- Commit: ${{ github.sha }}";
            echo "";
            echo "Artifacts:";
            echo "- coverage-report (HTML): coverage/lcov-report/index.html";
            echo "- lcov.info";
            echo "- vitest-output.txt";
          } >> "$GITHUB_STEP_SUMMARY"
