name: Test and Coverage

on:
  push:
    branches: ['**']
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate
        env:
          DATABASE_URL: "file:./test.db"

      - name: Push Prisma schema to test DB
        run: npx prisma db push
        env:
          DATABASE_URL: "file:./test.db"

      - name: Run tests with coverage
        run: npm run test:ci
        env:
          DATABASE_URL: "file:./test.db"

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: Print coverage summary
        if: always()
        run: |
          echo "--- Coverage text summary ---"
          cat coverage/coverage-final.json >/dev/null 2>&1 || true
          [ -f coverage/lcov.info ] && tail -n +1 coverage/lcov.info | head -n 50 || true